In [1]:
import numpy as np

In [ ]:
# 均匀分布
np.random.rand(10000)

#高斯分布
np.random.randn(10000)


In [2]:
tmp=np.random.randn(10000)
print(tmp)

[0.53564439 1.71754202 1.38312696 ... 0.47107723 2.27370764 0.87396142]


In [4]:
print(np.sum(tmp<0))

5106


In [5]:
print(np.sum(tmp>0.5))

3036


In [8]:
print(np.sum(tmp>3))

12


In [15]:
dots=np.random.rand(1000000,2)
print(dots)

[[0.58987082 0.90566294]
 [0.52420995 0.73996328]
 [0.869544   0.47013739]
 ...
 [0.63156306 0.82565033]
 [0.15011572 0.0692619 ]
 [0.34706435 0.13866492]]


In [11]:
np.min(dots)

2.304003648467834e-05

In [16]:
radii=np.sqrt(dots[:,0]**2+dots[:,1]**2)
print(radii)

[1.0808205  0.9068306  0.98850186 ... 1.03950487 0.16532374 0.37374005]


In [17]:
print(np.sum(radii<=1))

785546


In [14]:
print(np.pi/4)

0.7853981633974483
